[package]
name = "torrent"
version = "0.1.0"
edition = "2021"

[dependencies.bencode]
path = "../bencode"



[dependencies.uttd]
path = "../uttd"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
